[project]
name = "volatilityforecast"
version = "0.1.0"
description = "Application of neural networks with attention mechanism for forecasting economic instability."
requires-python = ">=3.14"
dependencies = [
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
    "yfinance>=1.1.0",
]
